//import { TicketKind, TicketStatus, TicketTag } from "../../interfaces/enums";
import type { Ticket } from "../../interfaces/Ticket";

export const mockTickets: Ticket[] = [
  // {
  //   id: "T-001",
  //   date: new Date(),
  //   kind: TicketKind.NOTICIA,
  //   operatorLabel: "OPERACIONES",
  //   title: "SOLUCIONADO TEMA LOGINS / ACTUALIZACIÓN DE CERTIFICADOS",
  //   details: "Se verificó acceso desde puestos y se normalizó el ingreso.",
  //   status: TicketStatus.CERRADO,
  //   tags: [TicketTag.IMPORTANTE],
  //   mentions: ["monica", "arturo"],
  //   audit: {
  //     createdAt: new Date(),
  //     createBy: { id: "u1", name: "Hernán" },
  //     closedAt: new Date(),
  //     closedBy: { id: "u1", name: "Hernán" },
  //   },
  // },
  // {
  //   id: "T-002",
  //   date: new Date(Date.now() - 1000 * 60 * 25),
  //   kind: TicketKind.INGRESO,
  //   site: "ALVEAR",
  //   operatorLabel: "SISTEMA",
  //   title: "INGRESO A SITIO: VISITA PROGRAMADA",
  //   details: "Se coordina ingreso con seguridad. Confirmar horario.",
  //   status: TicketStatus.CERRADO,
  //   tags: [TicketTag.RECORDATORIO, TicketTag.MENCIONES],
  //   mentions: ["leopoldo"],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 25),
  //     createBy: { id: "u2", name: "Sistema" },
  //   },
  // },
  // {
  //   id: "T-002",
  //   date: new Date(Date.now() - 1000 * 60 * 25),
  //   kind: TicketKind.INGRESO,
  //   site: "ALVEAR",
  //   operatorLabel: "SISTEMA",
  //   title: "INGRESO A SITIO: VISITA PROGRAMADA",
  //   details: "Se coordina ingreso con seguridad. Confirmar horario.",
  //   status: TicketStatus.CERRADO,
  //   tags: [TicketTag.RECORDATORIO, TicketTag.MENCIONES],
  //   mentions: ["leopoldo"],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 25),
  //     createBy: { id: "u2", name: "Sistema" },
  //   },
  // },
  // {
  //   id: "T-002",
  //   date: new Date(Date.now() - 1000 * 60 * 25),
  //   kind: TicketKind.INGRESO,
  //   site: "ALVEAR",
  //   operatorLabel: "SISTEMA",
  //   title: "INGRESO A SITIO: VISITA PROGRAMADA",
  //   details: "Se coordina ingreso con seguridad. Confirmar horario.",
  //   status: TicketStatus.CERRADO,
  //   tags: [TicketTag.RECORDATORIO, TicketTag.MENCIONES],
  //   mentions: ["leopoldo"],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 25),
  //     createBy: { id: "u2", name: "Sistema" },
  //   },
  // },
  // {
  //   id: "T-002",
  //   date: new Date(Date.now() - 1000 * 60 * 25),
  //   kind: TicketKind.INGRESO,
  //   site: "ALVEAR",
  //   operatorLabel: "SISTEMA",
  //   title: "INGRESO A SITIO: VISITA PROGRAMADA",
  //   details: "Se coordina ingreso con seguridad. Confirmar horario.",
  //   status: TicketStatus.ABIERTO,
  //   tags: [TicketTag.RECORDATORIO, TicketTag.MENCIONES],
  //   mentions: ["leopoldo"],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 25),
  //     createBy: { id: "u2", name: "Sistema" },
  //   },
  // },
  // {
  //   id: "T-002",
  //   date: new Date(Date.now() - 1000 * 60 * 25),
  //   kind: TicketKind.INGRESO,
  //   site: "ALVEAR",
  //   operatorLabel: "SISTEMA",
  //   title: "INGRESO A SITIO: VISITA PROGRAMADA",
  //   details: "Se coordina ingreso con seguridad. Confirmar horario.",
  //   status: TicketStatus.ABIERTO,
  //   tags: [TicketTag.RECORDATORIO, TicketTag.MENCIONES],
  //   mentions: ["leopoldo"],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 25),
  //     createBy: { id: "u2", name: "Sistema" },
  //   },
  // },
  // {
  //   id: "T-003",
  //   date: new Date(Date.now() - 1000 * 60 * 70),
  //   kind: TicketKind.PROCESO_Z15,
  //   operatorLabel: "Z/OS",
  //   title: "PROCESO Z15: VALIDAR JOBS POST-IPL",
  //   details: "Revisar colas, servicios y alarmas principales.",
  //   status: TicketStatus.ABIERTO,
  //   tags: [TicketTag.RECORDATORIO],
  //   mentions: [],
  //   audit: {
  //     createdAt: new Date(Date.now() - 1000 * 60 * 70),
  //     createBy: { id: "u1", name: "Hernán" },
  //   },
  // },
];
